version: "3.8"

services:
  app:
    container_name: sk-app
    image: skull-king
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    volumes:
      - .:/app
    ports:
      - ${APP_PORT:-3000}:3000
  mongodb:
    container_name: sk-mongo
    image: mongo:6.0.8
    restart: always
    ports:
      - ${MONGODB_PORT:-27017}:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  mailhog:
    container_name: sk-mailhog
    image: mailhog/mailhog
    ports:
      - '${MAILHOG_PORT:-1025}:1025'
      - '${MAILHOG_DASHBOARD_PORT:-8025}:8025'
  redis:
    container_name: sk-redis
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local
