version: "3.8"

services:
  skullking-app:
    container_name: skullking-app
    image: skullking-app
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    volumes:
      - .:/app
    ports:
      - ${APP_FORWARD_PORT:-3000}:3000
  skullking-mongo:
    container_name: skullking-mongo
    image: mongo:6.0.8
    ports:
      - ${MONGODB_FORWARD_PORT:-27017}:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

volumes:
  mongodb-data:
    driver: local
